# Generated by Django 3.2.16 on 2022-11-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createcate',
            options={'ordering': ['name', 'slug']},
        ),
        migrations.RemoveField(
            model_name='postcate',
            name='slug',
        ),
        migrations.AddField(
            model_name='createcate',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
