# Generated by Django 3.2.16 on 2023-01-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
